### Etapa 3 - EDA, Storytelling e VisualizaÃ§Ã£o

In [1]:
import pandas as pd

import re

In [2]:
dataframe_final_candidatos = pd.read_csv("etapa2_dataframe_final_candidatos.csv")

In [3]:
dataframe_final_candidatos.head()

,Data_Hora,IdTweet,Tweet,Candidato
0,2022-07-30 23:16:51+00:00,1553520025637625856,"@LulaOficial Exatamente, a verdade contra a su...",Lula
1,2022-07-30 23:16:51+00:00,1553520024891047943,@gleisi @LulaOficial @CamiloSantanaCE @elmanof...,Lula
2,2022-07-30 23:16:49+00:00,1553520017127374848,"O Manifesto do Direito via USP, com 500 mil as...",Lula
3,2022-07-30 23:16:49+00:00,1553520014518620162,@DeputadoFederal @LulaOficial 22ðŸ‡§ðŸ‡·ðŸ‡§ðŸ‡·ðŸ‡§ðŸ‡·ðŸ‡§ðŸ‡·ðŸ‡§ðŸ‡·ðŸ‡§ðŸ‡·,Lula
4,2022-07-30 23:16:49+00:00,1553520014342381569,"@LulaOficial Analisando, o molusco nÃ£o sai as ...",Lula

In [4]:
dataframe_final_candidatos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 153 entries, 0 to 152
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Data_Hora  153 non-null    object
 1   IdTweet    153 non-null    int64
 2   Tweet      153 non-null    object
 3   Candidato  153 non-null    object
dtypes: int64(1), object(3)
memory usage: 4.9+ KB

In [5]:
dataframe_final_candidatos.isnull().sum()

Data_Hora    0
IdTweet      0
Tweet        0
Candidato    0
dtype: int64

In [6]:
dataframe_final_candidatos['Tweet_limpo'] = dataframe_final_candidatos['Tweet']

In [7]:
dataframe_final_candidatos.head()

,Data_Hora,IdTweet,Tweet,Candidato,Tweet_limpo
0,2022-07-30 23:16:51+00:00,1553520025637625856,"@LulaOficial Exatamente, a verdade contra a su...",Lula,"@LulaOficial Exatamente, a verdade contra a su..."
1,2022-07-30 23:16:51+00:00,1553520024891047943,@gleisi @LulaOficial @CamiloSantanaCE @elmanof...,Lula,@gleisi @LulaOficial @CamiloSantanaCE @elmanof...
2,2022-07-30 23:16:49+00:00,1553520017127374848,"O Manifesto do Direito via USP, com 500 mil as...",Lula,"O Manifesto do Direito via USP, com 500 mil as..."
3,2022-07-30 23:16:49+00:00,1553520014518620162,@DeputadoFederal @LulaOficial 22ðŸ‡§ðŸ‡·ðŸ‡§ðŸ‡·ðŸ‡§ðŸ‡·ðŸ‡§ðŸ‡·ðŸ‡§ðŸ‡·ðŸ‡§ðŸ‡·,Lula,@DeputadoFederal @LulaOficial 22ðŸ‡§ðŸ‡·ðŸ‡§ðŸ‡·ðŸ‡§ðŸ‡·ðŸ‡§ðŸ‡·ðŸ‡§ðŸ‡·ðŸ‡§ðŸ‡·
4,2022-07-30 23:16:49+00:00,1553520014342381569,"@LulaOficial Analisando, o molusco nÃ£o sai as ...",Lula,"@LulaOficial Analisando, o molusco nÃ£o sai as ..."

In [8]:
def limpeza_do_texto(tweet):
  tweet = tweet.lower()
  tweet = re.sub('\n', '', tweet)
  tweet = re.sub('@[^\s]+', '', tweet)
  tweet = re.sub('\B#\S+', '', tweet)
  tweet = re.sub('https?://\S+|www\.\S+', '', tweet)
  return tweet

In [9]:
dataframe_final_candidatos['Tweet_limpo'] = dataframe_final_candidatos['Tweet'].apply(lambda i:limpeza_do_texto(i))

In [10]:
dataframe_final_candidatos.head()

,Data_Hora,IdTweet,Tweet,Candidato,Tweet_limpo
0,2022-07-30 23:16:51+00:00,1553520025637625856,"@LulaOficial Exatamente, a verdade contra a su...",Lula,"exatamente, a verdade contra a sua mentira. ðŸ˜¡ðŸ˜¡ðŸ˜¡ðŸ˜¡"
1,2022-07-30 23:16:51+00:00,1553520024891047943,@gleisi @LulaOficial @CamiloSantanaCE @elmanof...,Lula,sÃ³ rindo hahahahaha
2,2022-07-30 23:16:49+00:00,1553520017127374848,"O Manifesto do Direito via USP, com 500 mil as...",Lula,"o manifesto do direito via usp, com 500 mil as..."
3,2022-07-30 23:16:49+00:00,1553520014518620162,@DeputadoFederal @LulaOficial 22ðŸ‡§ðŸ‡·ðŸ‡§ðŸ‡·ðŸ‡§ðŸ‡·ðŸ‡§ðŸ‡·ðŸ‡§ðŸ‡·ðŸ‡§ðŸ‡·,Lula,22ðŸ‡§ðŸ‡·ðŸ‡§ðŸ‡·ðŸ‡§ðŸ‡·ðŸ‡§ðŸ‡·ðŸ‡§ðŸ‡·ðŸ‡§ðŸ‡·
4,2022-07-30 23:16:49+00:00,1553520014342381569,"@LulaOficial Analisando, o molusco nÃ£o sai as ...",Lula,"analisando, o molusco nÃ£o sai as ruas, bolson..."

In [11]:
dataframe_final_candidatos.to_csv('dataframe_final_candidatos_pronto_para_sentimento.csv', sep=',', index=False)